### ISSUE TITLE
compile failed on Fedora 27 64bits

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [aramg/droidcam#10]
when I run Make here are the result:

gcc -Wall  src/connection.c src/decoder.c src/droidcam.c -lgthread-2.0 -l:/usr/l                                                                                                              ib/libswscale.a  -l:/usr/lib/libavutil.a -l:/opt/libjpeg-turbo/lib`getconf LONG_                                                                                                              BIT`/libturbojpeg.a `pkg-config --libs --cflags gtk+-2.0` -lm -o droidcam
src/decoder.c: In function ‘decoder_prepare_video’:
src/decoder.c:321:60: error: ‘PIX_FMT_YUV420P’ undeclared (first use in this fun                                                                                                              ction); did you mean ‘AV_PIX_FMT_YUV420P’?
                 jpg_decoder.m_width, jpg_decoder.m_height, PIX_FMT_YUV420P, /*                                                                                                               src */
                                                            ^~~~~~~~~~~~~~~
                                                            AV_PIX_FMT_YUV420P
src/decoder.c:321:60: note: each undeclared identifier is reported only once for                                                                                                               each function it appears in
src/decoder.c: In function ‘decoder_share_frame’:
src/decoder.c:592:36: warning: passing argument 2 of ‘sws_scale’ from incompatib                                                                                                              le pointer type [-Wincompatible-pointer-types]
         sws_scale(jpg_decoder.swc, srcSlice, srcStride, 0, jpg_decoder.m_height                                                                                                              , dstSlice, dstStride);
                                    ^~~~~~~~
In file included from src/decoder.c:28:0:
/usr/local/include/libswscale/swscale.h:217:5: note: expected ‘const uint8_t * c                                                                                                              onst* {aka const unsigned char * const*}’ but argument is of type ‘uint8_t ** {a                                                                                                              ka unsigned char **}’
 int sws_scale(struct SwsContext *c, const uint8_t *const srcSlice[],
     ^~~~~~~~~
src/droidcam.c: In function ‘VideoThreadProc’:
src/droidcam.c:184:23: warning: cast from pointer to integer of different size                                                                                                                -Wpointer-to-int-cast]
  SOCKET videoSocket = (SOCKET) args;
                       ^
src/droidcam.c: In function ‘accel_callback’:
src/droidcam.c:288:16: warning: cast from pointer to integer of different size                                                                                                                -Wpointer-to-int-cast]
   thread_cmd = (int) user_data;
                ^
src/droidcam.c: In function ‘the_callback’:
src/droidcam.c:296:11: warning: cast from pointer to integer of different size                                                                                                                -Wpointer-to-int-cast]
  int cb = (int) extra;
           ^
src/droidcam.c:343:5: warning: ‘g_thread_create’ is deprecated: Use 'g_thread_ne                                                                                                              w' instead [-Wdeprecated-declarations]
     hVideoThread = g_thread_create(VideoThreadProc, (void*)s, TRUE, NULL);
     ^~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:108:0,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from src/droidcam.c:16:
/usr/include/glib-2.0/glib/deprecated/gthread.h:104:10: note: declared here
 GThread *g_thread_create       (GThreadFunc       func,
          ^~~~~~~~~~~~~~~
src/droidcam.c:343:53: warning: cast to pointer from integer of different size                                                                                                                -Wint-to-pointer-cast]
     hVideoThread = g_thread_create(VideoThreadProc, (void*)s, TRUE, NULL);
                                                     ^
src/droidcam.c: In function ‘main’:
src/droidcam.c:412:2: warning: ‘g_thread_init’ is deprecated [-Wdeprecated-decla                                                                                                              rations]
  g_thread_init(NULL);
  ^~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:108:0,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from src/droidcam.c:16:
/usr/include/glib-2.0/glib/deprecated/gthread.h:265:10: note: declared here
 void     g_thread_init                   (gpointer vtable);
          ^~~~~~~~~~~~~
src/droidcam.c:424:2: warning: ‘gdk_pixbuf_new_from_inline’ is deprecated [-Wdep                                                                                                              recated-declarations]
  gtk_window_set_icon(GTK_WINDOW(window), gdk_pixbuf_new_from_inline(-1, icon_in                                                                                                              line, FALSE, NULL));
  ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf.h:34:0,
                 from /usr/include/gtk-2.0/gdk/gdkpixbuf.h:37,
                 from /usr/include/gtk-2.0/gdk/gdkcairo.h:28,
                 from /usr/include/gtk-2.0/gdk/gdk.h:33,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from src/droidcam.c:16:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-core.h:362:12: note: declared                                                                                                               here
 GdkPixbuf* gdk_pixbuf_new_from_inline (gint          data_length,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:15: all] Error 1

Any idea?
thanks

**Comment by aramg** [comment]
`src/decoder.c:321:60: error: ‘PIX_FMT_YUV420P’ undeclared (first use in this function); did you mean ‘AV_PIX_FMT_YUV420P’?`

Hi, seems PIX_FMT_YUV420P was renamed to AV_PIX_FMT_YUV420P, try changing it in src/decoder.c (line 321) and see if that helps.

**Comment by ROBERT-MCDOWELL** [comment]
so far so good, works now, thanks!
