### ISSUE TITLE
HD Resolution output "squashed"

### ISSUE THREAD

**Issue by brackenhill-mob** [aramg/droidcam#109]
Running DroidcamX on Arch Linux

Changing resolution parameters in /etc/modprobe.d/droidcam.conf to 1280x720 or above (ie HD) results in Zoom/Google Meet etc output being "squashed" vertically. Highest res that doesn't get squashed is 960x720.

My Honor 6X has a resolution of 1920x1080 which I'd like to use for recording but cannot!

If this is expected behaviour, is there any way to get to use HD?

**Comment by aramg** [comment]
Did you also re- insert the module with 1280 720, or reboot the computer?
Whats the output of `ffplay /dev/video0` after you connect to the phone, assuming video0 is droidcam.

**Comment by brackenhill-mob** [comment]
Forgive me posting this as a bug - I believe(d) that it is given that it is v4l2loopback_dc which is causing/affecting this issue. Happy to take it to email if you prefer - just let me know here ;)

I tried all resolution settings in /etc/modprobe.d/droidcam.conf  and rebooted after each edit - for some reason I can't always remove the module even when trying to force it as Arch tells me that it is still in use.

The outputs for ffplay at various settings are below

At 960x720 (no squashing)

ffplay version n4.3.1 Copyright (c) 2003-2020 the FFmpeg developers
  built with gcc 10.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, video4linux2,v4l2, from '/dev/video0':B sq=    0B f=0/0
  Duration: N/A, start: 464.086301, bitrate: 248832 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 960x720, 248832 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc

At 1920x1080 differences from above is

Input #0, video4linux2,v4l2, from '/dev/video0':B sq=    0B f=0/0
  Duration: N/A, start: 90.231080, bitrate: 746496 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1920x1080, 746496 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc

And for 1280x720

Input #0, video4linux2,v4l2, from '/dev/video0':B sq=    0B f=0/0   
  Duration: N/A, start: 71.862758, bitrate: 331776 kb/s
    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720, 331776 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc

FWIW the last 2 settings are squashed in ffplay too.

**Comment by aramg** [comment]
Looks correct.
Just to confirm, you have DroidCamX open on the phone, not the free app (they are independent of each other).

Either the client is getting the wrong params, or the phone app is not sending a 16:9 stream.
If you open the IP cam viewer in a browser (the http://... URL the app shows), can you pick 720p HD and 1080p FHD options and get 16:9 image? Or are those squashed too.

**Comment by brackenhill-mob** [comment]
Don't have the free app installed

The browser viewer isn't squashing.

Weird ... :)

**Comment by brackenhill-mob** [comment]
Well now it gets even weirder. Arch, being a rolling release OS, has done an update of something and now it works as expected. This can be closed.
