### ISSUE TITLE
Protocols?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [aramg/droidcam#11]
Hi,
what protcols droidcam uses?
thanks

**Comment by aramg** [comment]
HI, The app implements MJPEG over MJPEG, otherwise the client and the app use a simple custom protocol.

**Comment by ROBERT-MCDOWELL** [comment]
ok thanks, do you think it would be easy to expand droidcam to standard protocols ont he web
like rtmp, rtmfp, ws, http ?

**Comment by aramg** [comment]
It wouldn't be trivial. I have experimented with H.264 over RTMP, but the delay in video is too noticeable - the app needs to be as real time as possible (a few milliseconds at most).

**Comment by ROBERT-MCDOWELL** [comment]
but what about in raw mode without to encode?

**Comment by ROBERT-MCDOWELL** [comment]
unless if the encoding is happening aftere the sink ;)

**Comment by ROBERT-MCDOWELL** [comment]
aramg, to be frank I would love to use your droidcam driver
to capture my (win/mac/android/ios) desktop. is it possible?

**Comment by aramg** [comment]
Hi, I cannot comment on screen capture, I'm sure its possible. I am closing this now as offtopic.
If you have any specific issues with the code here, please open a new issue.

**Comment by ctrxok** [comment]
> Hi, The app implements MJPEG over HTTP, otherwise the client and the app use a simple custom protocol.

can i chance protocol to RSTP
