### ISSUE TITLE
Work with standard v4l2loopback

### ISSUE THREAD

**Issue by AstraLuma** [aramg/droidcam#110]
As it stands, the packaged v4l2loopback module conflicts with the standard one (they appear to have the same name), and droidcam is incompatible with it.

Please either differentiate your module from the standard one, or adjust so that you have compatibility with standard v4l2loopback.

**Comment by aramg** [comment]
Can you elaborate, how do the modules conflict?
Where do they appear to be the same, the dc version should appear as "DroidCam" or as `/dev/videoX`

**Comment by AstraLuma** [comment]
is the module not called `v4l2loopback`?

**Comment by aramg** [comment]
Not exactly, its got a suffix  `v4l2loopback-dc`

**Comment by AstraLuma** [comment]
oh ok
