### ISSUE TITLE
How to flip the image?

### ISSUE THREAD

**Issue by jakubiakdev** [aramg/droidcam#111]
The documentation provides an explanation on how to do a 90 degree rotation, how about 180?
I bought droidcamx for it, flipping works in browser (ip of the phone) but I want to use it as a webcam
(Also if someone thinks _just flip your phone you idiot_ - with my setup I can't do it)

**Comment by brackenhill-mob** [comment]
There are orientation apps in the play store which can do what you want. No 
ideal but may be a solution for you.
--

**Comment by jakubiakdev** [comment]
So you can rotate the app to rotate the image that is sent out?

**Comment by brackenhill-mob** [comment]
I used this on another webcam app to do reverse landscape ages ago before I 
found DroidcamX and it worked for me. YMMV. I used an app called Screen 
Orientation. HTH.
--

**Comment by jakubiakdev** [comment]
I guess that's too late for me because I already went with a different solution 😅. I'm gonna leave the issue though, I want someone to confirm that this is an actuall working solution.

**Comment by aramg** [comment]
90 degree rotation was possible using the webcam inversion trick. 180 isnt available, its easy enough to rotate the phone physically (in most cases).

The Windows client uses D2D/GDI to apply the transforms, on Linux the client needs to use OpenGL or SDL. See #38.
