### ISSUE TITLE
Documentation should state that ./install-dkms is debian-based only 

### ISSUE THREAD

**Issue by jakubiakdev** [aramg/droidcam#112]
As the title, it uses debian packaging. No good for arch and others

**Comment by aramg** [comment]
AFAIK it works on some other distros, too.
There haven't been any issues reported so far, whats the error on Arch?

**Comment by jakubiakdev** [comment]
It makes a debian package (`dmks mkdeb`). Of course unsupported on distros that aren't Debian

**Comment by brackenhill-mob** [comment]
Works fine on Arch using the package in AUR. I use it almost daily ;)
--

**Comment by jakubiakdev** [comment]
AUR package doesn't use the ./install-dkms script

**Comment by aramg** [comment]
Reviewed the code, you are correct.
```
if [ -f /etc/redhat-release ]; then
      dkms mkrpm -m ${V4L2_LOOPBACK_DC} -v ${V4L2_LOOPBACK_VERSION}
else
      dkms mkdeb -m ${V4L2_LOOPBACK_DC} -v ${V4L2_LOOPBACK_VERSION}
fi
```

I didnt write the dkms installer and am not sure what the equivalent is for Arch, but it looks like we just need another if case.
