### ISSUE TITLE
Install issue for Ubuntu 20.10

### ISSUE THREAD

**Issue by dylanpjx** [aramg/droidcam#113]
I have performed `sudo apt install linux-headers-$(uname -r)`. I tried to perform `gcc make linux-headers-$(uname -r)` but got `gcc: error: make: No such file or directory`. I've also checked that the directory for the linux header is indeed present.

`sudo ./install` returns this error
```
ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.
```

`sudo ./install-dkms` returns this error
```
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.8.0-7625-generic all KVERSION=...(bad exit status: 2)
ERROR (dkms apport): binary package for v4l2loopback_dc: 0.0.1 not found
Error! Bad return status for module build on kernel: 5.8.0-7625-generic (x86_64)
```

**Comment by dylanpjx** [comment]
I'm guessing the `v4l2loopback` is missing in the current kernel, tried doing `sudo apt install v4l2loopback-dkms` and getting `linux-headers-5.8.0-7625-generic is not supported`.

**Comment by aramg** [comment]
Hi,
1. as mentioned in the issue template this is NOT a support forum.
2. You need to run  `sudo apt install gcc make linux-headers-$(uname -r)`, but it sounds like your system might be in a bad state.
