### ISSUE TITLE
Droidcam do not create audio device on Ubuntu 20.04

### ISSUE THREAD

**Issue by davepee** [aramg/droidcam#114]
Hi,

after `./install` a ran .`/install-sound`. `snd_aloop` module is loaded. Devices `Loopback [Loopback], zařízení 0: Loopback PCM [Loopback PCM]` created. But if droidcam is starting there is no audio device opened:

> Device /dev/video0 is 'Droidcam'
> Opened /dev/video0, fd:10

What is wrong?

**Comment by aramg** [comment]
Are you sure it did not load?
You should see video and audio device info on the droidcam window, at the bottom
