### ISSUE TITLE
Failed to allocate a buffer: ../sys/v4l2/gstv4l2src.c(1024): gst_v4l2src_create (): /GstCameraBin:camerabin/GstWrapperCameraBinSrc:camera_source/GstBin:bin36/GstV4l2Src:v4l2src2

### ISSUE THREAD

**Issue by mykaul** [aramg/droidcam#116]
**Describe the bug**
'Cheese' is not able to maintain video from the camera - it starts, then stops. The above message is what I've found in journalctl.

**Expected behavior**
Work is previously (1.5) did.

**Additional context**
Fedora, 5.8.17-300.fc33.x86_64

Don't recall seeing such a failure in previous releases.

Doesn't seem to happen in Google Meet, for example.

**Comment by aramg** [comment]
Looks like a Cheese problem. The video driver did not change between 1.5/1.6.
