### ISSUE TITLE
32bit compile fails 

### ISSUE THREAD

**Issue by netplayer** [aramg/droidcam#119]
On an old 486 machine (Xubuntu12)  g++: error: unrecognized option ‘-no-pie’ . Dependencies and README instructions double checked.  Any workaround / advise to get a 32bit binary?

**Comment by aramg** [comment]
Your g++ is too old. Try to remove `-no-pie' in the Makefile. If it fails, you'll need to find the equivalent/alternative options for the older machine. Ubuntu 12 is obsolete and long past its end-of-life.
