### ISSUE TITLE
droidcam-cli usb connection

### ISSUE THREAD

**Issue by ettom** [aramg/droidcam#17]
Not sure if I'm missing something, but there doesn't seem to be an option to connect to droidcam via usb using droidcam-cli on linux. Everything works fine from the GUI, but I want to run droidcam on a system without X.

**Comment by ettom** [comment]
It seems the solution is to run `droidcam-cli 127.0.0.1 <port>`. Seems rather obvious now, but it would be nice if this was documented somewhere.

**Comment by aramg** [comment]
Hi,
Will look at adding a note on that.

The Gui client runs
adb forward tcp:$port tcp:$port

and connects via 127.0.0.1, yes.

You'll need to setup the port forwarding manually if USB gets reconnected.

**Comment by GavinLilly** [comment]
Hello.

Sorry to revive an old thread but I made a systemd file to automatically setup ADB forwarding and droidcam-cli. I did this because I have an old phone connected to my PC permanently and I didn't want to have to start Droidcam manually every time I use the machine.

```
[Unit]
Description=Start droidcam in the background

[Service]
ExecStartPre=adb forward tcp:4747 tcp:4747
ExecStart=droidcam-cli 127.0.0.1 4747
ExecStopPost=adb forward --remove tcp:4747

[Install]
WantedBy=multi-user.target
```

I intend to make a PR for it but want to see about adding the installation of it to the install script first.

**Comment by aramg** [comment]
Thanks, this seems it would be more appropriate to go into a Wiki somewhere.
I am planning to port the ADB handling from the latest Windows client and will need to think about how to incorporate it into the cli version as well.

**Comment by jarthod** [comment]
@aramg thanks for this very useful tool and the nice Linux support ! I just want to add my vote on this, it's also the only thing I currently would like to see added: being able to start USB connection from CLI (`--usb` or something)

**Comment by aramg** [comment]
http://www.dev47apps.com/files/linux/droidcam_cli_12.zip
Added an option connect over adb. 
Will wait for some feedback before releasing.
```
droidcam-cli [-a] [-v] <ip> <port>
   Connect to ip:port with audio and/or video

droidcam-cli [-a] [-v] adb <port>
   Connect via adb with audio and/or video
```

**Comment by jarthod** [comment]
Awesome, I just gave it a try and it worked perfectly for me :movie_camera: 
```
> ./droidcam-cli adb 4747
Device /dev/video0 is 'Droidcam'
Opened /dev/video0, fd:3
Audio loopback device not found.
Is snd_aloop loaded?
Client v1.2
Video: /dev/video0
connecting to 127.0.0.1:4747
```

**Comment by jfacemyer** [comment]
This works for me too!

**Comment by darklyn3r** [comment]
> It seems the solution is to run `droidcam-cli 127.0.0.1 <port>`. Seems rather obvious now, but it would be nice if this was documented somewhere.

So it is, thanks
