### ISSUE TITLE
[Workaround] Droidcam blank picture on Discord

### ISSUE THREAD

**Issue by fosspill** [aramg/droidcam#18]
Hi!

Currently, at least on my two machines, droidcam does not produce a picture when used through Discord. 

I'm noting down the workaround I ended up using, in hopes that it might help figure out the issue:

1. Install v4l2loopback for your kernel (you'll now have both v4l2loopback and v4l2loopback-dc).
2. Install ffmpeg if it's missing
3. Restart
4. Ensure that droidcam works in VLC, for instance.
5. Run `sudo modprobe v4l2loopback video_nr=9 card_label="DroidCam Repeat"`
6. Run `ffmpeg -re -i /dev/video0  -f v4l2 /dev/video9`
Replace video0 with your droidcam device. VLC will easily show you which one it is.
7. Change Discord to using the "DroidCam Repeat" device. It now works!

**Comment by aramg** [comment]
Hi, thanks,
what distro and kernel are you using?

**Comment by fosspill** [comment]
Arch and Kernel 5.3.9 atm :)

**Comment by aramg** [comment]
Tested+fixed Discord on Lubuntu 19.10.
http://www.dev47apps.com/droidcam/linuxx/ links updated with new client.
