### ISSUE TITLE
Linux Desktop client droidcam-v4l2-x64 does not connect with DroidCam 6.3 Android App

### ISSUE THREAD

**Issue by dmanev** [aramg/droidcam#2]
With the latest update of DroidCam 6.3 on my phone. I'm no longer being able to connect with my Linux client droidcam-v4l2-x64
The desktop client raises error:

MSG_ERROR("Connection reset!\nDroidCam is probably busy with another client");

although the android app says: "Desktop client is outdated"
which in my opinion is the correct statement.

**Comment by aramg** [comment]
Thanks for the report.
64-bit binaries updated at: http://www.dev47apps.com/droidcam/linuxx/

https://github.com/aramg/droidcam/commit/d3ee456adca75252e484efafd0c1ce45969843be

**Comment by dmanev** [comment]
Thanks for the quick response. I actually didn't have time to clone the repo, so it wasn't 100% correct to raise the issue here. Anyway the new package works fine !
