### ISSUE TITLE
insmod: ERROR: could not insert module /lib/modules/5.3.0-42-generic/kernel/drivers/media/video/v4l2loopback-dc.ko: Operation not permitted

### ISSUE THREAD

**Issue by argearriojas** [aramg/droidcam#21]
Hi,

I am trying to install the linux client by following instructions from: https://www.dev47apps.com/droidcam/linuxx/

I made sure the dependencies are installed by doing:
```
sudo apt-get install gcc make linux-headers-`uname -r`
```

When executing the install script, it fails when trying to insert the compiled module
`
insmod: ERROR: could not insert module /lib/modules/5.3.0-42-generic/kernel/drivers/media/video/v4l2loopback-dc.ko: Operation not permitted
`

Here's some extra info:
```
$ uname -a
Linux hostname 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I also tried installing `gcc-4.9`, but got the same error 
```
$ sudo ./install 
Webcam parameters: '640' and '480'
Building v4l2loopback-dc.ko
make: Entering directory '/tmp/droidcam-64bit/v4l2loopback'
make -C /lib/modules/`uname -r`/build M=`pwd`
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-42-generic'
  CC [M]  /tmp/droidcam-64bit/v4l2loopback/v4l2loopback-dc.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /tmp/droidcam-64bit/v4l2loopback/v4l2loopback-dc.mod.o
  LD [M]  /tmp/droidcam-64bit/v4l2loopback/v4l2loopback-dc.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-42-generic'
make: Leaving directory '/tmp/droidcam-64bit/v4l2loopback'
Moving driver and executable to system folders
Registering webcam device
insmod: ERROR: could not insert module /lib/modules/5.3.0-42-generic/kernel/drivers/media/video/v4l2loopback-dc.ko: Operation not permitted

$ gcc --version
gcc (Ubuntu 4.9.3-13ubuntu2) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Any clues about this?

**Comment by aramg** [comment]
Hi, 'Operation not permitted' usually means insufficient privileges. What do you get if you run `sudo su` then `whoami`?
Is there anything at the end of  /var/log/syslog after you get the error?

**Comment by GabVenturato** [comment]
Hi, I had the same problem. Try disabling secure boot if you have it enabled :)

**Comment by pdvrieze** [comment]
It could be selinux that is interfering here. Or you may be using signed modules (which I guess the very rudimentary build system doesn't support) - it is possible to sign by hand.

**Comment by gnud** [comment]
Hi,

had this problem for 3 days, and I found a method to sign it.

I managed to sign the module by hand, if anyone needs to sign the module you can use this method:

`mv v4l2loopback-dc.ko v4l2loopback-dc_unsigned.ko`

`sudo kmodsign sha512 /var/lib/shim-signed/mok/MOK.priv /var/lib/shim-signed/mok/MOK.der v4l2loopback-dc_unsigned.ko v4l2loopback-dc.ko`

`sudo ./install`

then I executed the droidcam which opens the gui and I initialized the streaming via wifi, on browser  I can use the camera :).

Tested on Kubuntu 18.x with working secure boot, using kernel 5.0.0-37-generic.
If you cannot remember the keys, you can reset the MOK, this will generate new private keys and you need to accept them in the bios, any existing signed modules needs to be reinstalled like virtualbox-dkms and others.

**Note**: I cannot build this repo without the last two PR's from @pdvrieze  , so make sure you got them patched locally.
What I did after PR applying patches is:

1. `cmake .`
2. `make`
3. cd v4l2loopback
4. make

then the rest of the ko signing process and installing stuff.

Thanks
-- Damjan

**Comment by aramg** [comment]
Hi all, sorry for not being more active, I've been dealing with Microsofts nonsense RE driver signing. Did you have to generate those certificates ? Sounds like I'll have to look into auto-detecting Secure boot and making the singing part of the build process.

**Comment by gnud** [comment]
`Sounds like I'll have to look into auto-detecting Secure boot and making the singing part of the build process.`
@aramg yes, I would suggest  signing process to be in the install script, and when the .ko is building to ends with "_unsigned" so that after building it can be signed with the real name.

However, some distros may have a different command to sign the kernel module, the solution I presented was for Ubuntu only, not sure how Rhel based system sign stuff.

`Did you have to generate those certificates ?`
I have the MOK certificate since I installed the OS, but you can reset it anytime (be careful).

To test it you can use virtualized OS, I am still learning how to use qemu with secure boot to test stuff, cause you will need fully working UEFI.
Here it is: https://fedoraproject.org/wiki/Using_UEFI_with_QEMU#Testing_Secureboot_in_a_VM

If you test it, please test it in Ubuntu VM, because the signing process I present is fully working. Afterwards test something for fedora or something.
Thanks.

**Comment by argearriojas** [comment]
Thanks for your replies, sorry I didn't check this out before. @gnud's solution worked nice, I too had the certificate in place and ready to use

**Comment by t-legiaw** [comment]
Hi all,

same problem here. But unfortunately  @gnud's solution is not working here. The signing step itself doesn't report an error.

When it comes to the install step it reports (again) "insmod: ERROR: could not insert module /lib/modules/5.3.0-42-generic/kernel/drivers/media/video/v4l2loopback-dc.ko: Operation not permitted"

tail -f /var/log/syslog
```
Mar 24 23:00:49 silie kernel: [50383.090242] videodev: Linux video capture interface: v2.00
Mar 24 23:00:49 silie kernel: [50383.091185] Lockdown: insmod: Loading of unsigned module is restricted; see man kernel_lockdown.7
```

**Comment by gnud** [comment]
> Hi all,
> 
> same problem here. But unfortunately @gnud's solution is not working here. The signing step itself doesn't report an error.
> 
> When it comes to the install step it reports (again) "insmod: ERROR: could not insert module /lib/modules/5.3.0-42-generic/kernel/drivers/media/video/v4l2loopback-dc.ko: Operation not permitted"
> 
> tail -f /var/log/syslog
> 
> ```
> Mar 24 23:00:49 silie kernel: [50383.090242] videodev: Linux video capture interface: v2.00
> Mar 24 23:00:49 silie kernel: [50383.091185] Lockdown: insmod: Loading of unsigned module is restricted; see man kernel_lockdown.7
> ```
> 
> note: Linux Mint 19.3 Tricia (which is based on Ubuntu 18.04 Bionic)
I also have these deb packages:
v4l2loopback-dkms
v4l2loopback-utils
if that can help.

Also try depmod -a -v after doing install and manually modprobe v4l2loopback_dc module.

**Comment by t-legiaw** [comment]
thanks  @gnud - but still no luck

**Comment by gnud** [comment]
> thanks @gnud - but still no luck
> 
> Finally I turned off _Secure Boot_ (inside the UEFI Bios). And now the module is loading :-)

Hi, 

@t-legiaw The problem with that is someday you will install a package that will force you to have signed modules (I hope not) or you will buy a laptop that has no option to disable the secure boot(only to reset the certificates). I suggest you experiment on a virtual machine to learn the full process, I managed somehow. but there are still some things to learn.

@aramg Can you write unit tests to provide these things.
It could test the building of the module and provide all the steps like:
- OS has valid UEFI certificates (mark to use signing)
- is the built module unsigned valid (like some kernel module check) 
- is the signed module really valid (if signing mode)
- test load the kernel module in-place (not copying it to the system)
- test copying the kernel module in the system the loading it again
(then removing it with unload first)

I can help if you like.

Thanks.

**Comment by aramg** [comment]
Without going crazy with the auto-magic singing across all distros, here is a simple check: https://github.com/aramg/droidcam/pull/29

It would be nice to compile the defaults paths for various distros (`/var/lib/shim-signed/mok/MOK.priv` is only Ubuntu ?) to make it work for a larger group of users out of the box

**Comment by sanjailal** [comment]
> Hi, I had the same problem. Try disabling secure boot if you have it enabled :)

Thanks dude. It helped me solve my problem.

**Comment by maheshsundaram** [comment]
It looks like the `install-video` script now includes signing, however it still fails for me at `insmod` with `Operation not permitted` 

I have secure boot enabled. 

I attempted to use the hand signing method that @gnud shares above. I did this in the `/lib/modules/5.15.0-47-generical/kernel/drivers/media/video` directory and I did not get any error. But trying `insmod v4l2loopback-dc.ko width=640 height=480` I get the same `Operation not permitted error`. 

I am able to use droidcam when I disable secure boot, but it would be really nice to figure out the signing.

**Comment by maheshsundaram** [comment]
Update: I was able to solve the issue by following this guide - https://superdanby.github.io/Blog/signing-kernel-modules-for-secure-boot.html

1. Turn off secure boot
2. Run ./install-client and ./install-video
3. Follow the above guide to sign the module
4. Reboot and enroll the MOK
5. Reboot and turn on secure boot

Droidcam works now for me with secure boot!
