### ISSUE TITLE
DroidCamX not working but DroidCam is on Ubuntu 18.04 (subsampling error).

### ISSUE THREAD

**Issue by SamGuay** [aramg/droidcam#24]
While the DroidCam works through USB-A smoothly, I tried it with DroidCamX to improve the quality, but it's not working. I get this message:  `Error: Unexpected video image stream subsampling` in my terminal every other second. It seems I can't change the resolution despite following the [instructions](https://www.dev47apps.com/droidcam/linuxx/) (doesn't do anything even if I edit the config file).

I've looked into the code to understand why I get this error, but it's not obvious to me why it does so. 

Currently using this on a Ubuntu 18.04 machine with a Pixel 3 in adb mode.

Do you need more info to help me out?

Best,

**Comment by aramg** [comment]
Hi, did anything at all change other than the app?
If you swap back to DroidCam it "just works"?
Can you paste the first couple lines the client output when you connect (not the error, just the resolution part mainly)

**Comment by SamGuay** [comment]
Thanks for the quick reply! 

Nothing changes except the app. Here's what I did to obtain the output below:
1. Open DroidCam in my terminal
1. Open DroidCam App on my phone
1. Connect both together through the "*GUI*" provided (no offense, but maybe we could improve this, I'm not a developer myself, but happy to try out during the crisis..)
1. Close DroidCam App and shutdown DroidCam on my computer.
1. Repeat previous steps but with DroidCamX.
```
(base) sam@aims:~$ droidcam
Device: Integrated Camera: Integrated C
Device: Integrated Camera: Integrated C
Device: Droidcam
Found driver: /dev/video2 (fd:12)
connecting to 127.0.0.1:4747
^C
(base) sam@aims:~$ echo "now trying DroidCamX"
now trying DroidCamX
(base) sam@aims:~$ droidcam
Device: Integrated Camera: Integrated C
Device: Integrated Camera: Integrated C
Device: Droidcam
Found driver: /dev/video2 (fd:12)
connecting to 127.0.0.1:4747
error: need a temp buffer, this shouldnt happen!
error: need a temp buffer, this shouldnt happen!
error: Unexpected video image dimensions
Error: Unexpected video image stream subsampling
Error: Unexpected video image stream subsampling
Error: Unexpected video image stream subsampling .. forever
```


Note that my computer detects the app because I can see in DroidCamX the view (which seems wider than a normal 16:9 to my eyes, but I might be wrong. 

Many thanks!

**Comment by ImanolFla** [comment]
Hi,

I'm experiencing the exact same problem as described by @SamGuay on my machine (Ubuntu 18.04 LTS with kernel 5.3.0-42-generic). The issue arises only when using DroidCamX, while everything seems to work correctly with DroidCam. On top of the above I have observed the following:

- Accessing the IP camera from the browser (`localhost:4747`) works well also with DroidCamX
- Playing the stream in /dev/video0 with GStreamer:
`gst-launch-1.0 v4l2src device=/dev/video0 ! xvimagesink`
works well only with DroidCam (unfortunately with DroidCamX it yields a black output)
- Interestingly enough, after connecting my phone to my machine (via USB) through the Linux client and then stopping the connection (keeping the USB cable connected), I was still able to access my phone's camera through VLC:
`vlc http://localhost:4747/video?1920x1080`
This worked with both DroidCam and DroidCamX
- Everything else (e.g. Skype, cheese, etc...) works only with DroidCam

I hope this information is useful for debugging :smiley: 

Many thanks!

**Comment by aramg** [comment]
@SamGuay were you using 1080p as well?
Does DroidCamX work OK at 1280x720?

**Comment by ImanolFla** [comment]
> Does DroidCamX work OK at 1280x720?
Yes, DroidCamX works well at 1280x720

**Comment by aramg** [comment]
OK, then the problem is with decoding 1080p streams. Will check it out

**Comment by SamGuay** [comment]
I confirm, DroidCamX doesn't output any error when the resolution is changed to 1280x720.

**Comment by aramg** [comment]
The following binaries work for me with 1080p streams:
https://www.dev47apps.com/droidcam_1080fix.zip

If I could get extra verification, I'll prep a proper update.

**Comment by SamGuay** [comment]
Hi, I tried to get this working, but I'm stuck with this message:
```
(base) sam@aims:~/Downloads$ ./droidcam
./droidcam: error while loading shared libraries: libswscale.so.5: cannot open shared object file: No such file or directory
```
From what I understand, this is related to ffmpeg. So I updated ffmpeg, but no success yet...

**Comment by morsik** [comment]
I can confirm I the same problem. Works in 720p, but not in 1080p. Same error in terminal:
Run on Fedora 31 with latest patches to compile (at talked in other places).

I specifically bought DroidCamX version to get 1080p :(

**Comment by aramg** [comment]
Did you try installing libswscale specifically ? Try to go for libswscale-dev.
(afaik it should be a dependency for ffmpeg, but maybe not. I'll go back to static linking in the final release)

**Comment by aramg** [comment]
@morsik  could you try the updated I posted above ?

**Comment by flamarique** [comment]
@aramg I can confirm that these binaries work on my system with 1080p streams :smiley: 

@SamGuay I also got the same error message. The problem is that the latest version of libswscale for Ubuntu 18.04 is different from the one used to compile the binaries, so it can't find them at runtime.

To fix this I had to install the latest version manually and link to it when running droidcam. The steps are:

1. Download and untar ffmpeg:
`wget https://ffmpeg.org/releases/ffmpeg-4.2.2.tar.bz2`
`tar xfj ffmpeg-4.2.2.tar.bz2`

2. Change to directory
`cd ffmpeg-4.2.2/`

3. Configure:
`./configure --prefix=/path/to/local/installation/local-ffmpeg --enable-shared --disable-x86asm`
Notice that I've used a local installation to avoid clashing with the version installed through `apt`. You need to modify your local installation path in the above command, i.e. `/path/to/local/installation`

4. Build and install locally (install to the path specified in `--prefix` at `configure` step):
`make -j8 && make install`

5. Finally, go to wherever you have your droidcam binaries and type:
`env LD_LIBRARY_PATH=/path/to/local/installation/ffmpeg/lib ./droidcam`

It should work now :)

**Comment by morsik** [comment]
@aramg I can confirm it works in FullHD with those binaries.

**Comment by aramg** [comment]
Awesome, thanks for confirming!
I'll switch back to static linking, despite all the pushback its just more portable, and update the official downloads today.

**Comment by morsik** [comment]
@flamarique I don't think you need to build your own ffmpeg…

I don't know how about Ubuntu, but on Fedora libswscale is bundled with ffmpeg and it's in ffmpeg-devel package (so something like ffmpeg-dev for Debian-based?), but the actual header is in `/usr/include/ffmpeg` not in `/usr/include` and I had to update Makefile to make it work (probably some pkg-config should do better job).

**Comment by flamarique** [comment]
@morsik Unfortunately, I'm afraid you do need to build your own ffmpeg in Ubuntu 18.04. I already had libswscale-dev installed through `apt` but that only provided me with `libswscale.so.4` (the binaries expected version `5`)

**Comment by aramg** [comment]
yep I built those on Lubuntu 19

**Comment by flamarique** [comment]
Both `libm.so.6` and `libc.so.6` are present in my Ubuntu 18.04

**Comment by morsik** [comment]
@flamarique oh, my bad. You said about provided binaries - I misunderstond! I mentioned this because @aramg told he'll switch to static binaries… but they are bad in terms of source code and real building from source code.

They are fine for distributing working versions tough, and I was confused about what he want to "switch back to static linking".

**Comment by aramg** [comment]
Latest build, tried on Lubuntu 14, 16, and 19.
https://www.dev47apps.com/files/linux/droidcam_latest.zip

**Comment by SamGuay** [comment]
Great, many thanks for all the effort! :raised_hands: 

Just reinstalled it and it seems to be working as intended.
