### ISSUE TITLE
Installing on Fedora 22

### ISSUE THREAD

**Issue by mprogram** [aramg/droidcam#3]
get error message after sudo sh install on Fedora 22, all dependencies, excluding 
libavutil-dev
libswscale-dev, installed
...
Moving driver and executable to system folders
cp: cannot stat «droidcam»: No such file

**Comment by aramg** [comment]
The install script is for the final install package.
run `make droidcam` and `make cli` first to get the executables.

**Comment by mprogram** [comment]
I installed the ffmpeg 3 from official website
(because I didn't find in Fedora repos libavutil-dev,libswscale-dev, after this  received message:
/bin/ld: cannot find -l:/usr/lib/libswscale.a
/bin/ld: cannot find -l:/usr/lib/libavutil.a
/bin/ld: cannot find -l:/opt/libjpeg-turbo/lib64/libturbojpeg.a
collect2: error: execution of ld completed with return code 1
The Makefile: 15: the recipe is a mistake for the purpose of «all»
)
after this I run make install, and get error
src/decoder.c: In function «decoder_prepare_video»:
src/decoder.c:321:60: error: «PIX_FMT_YUV420P» undeclared (first use in this function)
                 jpg_decoder.m_width, jpg_decoder.m_height, PIX_FMT_YUV420P, /*
