### ISSUE TITLE
altered webcam resolution is non-permament

### ISSUE THREAD

**Issue by tomthecat** [aramg/droidcam#34]
**steps to reproduce**
 
1. Close any programs using the droidcam webcam. Unload the device driver:
` sudo rmmod v4l2loopback_dc`

2. Re-load it with new resolution: 
`sudo insmod /lib/modules/uname -r/kernel/drivers/media/video/v4l2loopback-dc.ko width=1280 height=720`

3. Restart the droidcam client: Works with 720p resolution.

4. Edit the text file /etc/modprobe.d/droidcam.conf with the new options to make the change stick:
`options v4l2loopback_dc width=1280 height=720`
 
5. reboot

**actual behaviour**

Despite the droidcam.conf entries, the resolution falls back to 640 x 480.

**expected behaviour**

The changes in resolution should be permanent.

**version number**
DroidCamX 6.7.3
latest Linux client from https://www.dev47apps.com/files/linux/droidcam_latest.zip (downloaded on 04/01/20)

**operating systems**
mobile: Android 9
desktop: openSUSE Leap 15.1 w/ KDE and kernel 5.3.8

**Comment by aramg** [comment]
Thanks, I'll try to reproduce this, haven't tested this flow in a while

**Comment by aramg** [comment]
Seems to work fine in Lubuntu 19. 
Are you sure you edited the file as root and it was saved correctly?

**Comment by tomthecat** [comment]
You are right, it works. It was an artifact of my webcam app which let me think something was wrong with the resolution.
