### ISSUE TITLE
Build failure if path has space

### ISSUE THREAD

**Issue by aso824** [aramg/droidcam#37]
If path has space, for example `/home/some user/droidcam`, build fails in v4l2loopback step.

Tried to fix it but without success, something is wrong with this:

    all:
	    make -C /lib/modules/`uname -r`/build M=`pwd`

Adding quotes does not help and I couldn't discover what does `M` argument stands for.

**Comment by aramg** [comment]
Try adding quotes around "`pwd`"

**Comment by aso824** [comment]
Tried that, as I said:

> Adding quotes does not help

Weird output was returned and I couldn't understand where is the bug.
I managed to install it without problems, but my less technical friend stumbled upon this - he put files inside "New folder" and this happened.

**Comment by aramg** [comment]
The M=PATH is a target in `/lib/modules/$(uname -r)/build/Makefile`, so this is an 'issue' with the linux kernel.
