### ISSUE TITLE
FEDORA 31 x86-64 : Could not install => insmod : could not insert module

### ISSUE THREAD

**Issue by SitpiRajendran** [aramg/droidcam#39]
Hello guys,

I am trying to install DroidCam on my fedora, but i couldn't. I tried modprobe etc.. but it always failing can you help me ?

There is my error :
```bash
➜ droidcam-64bit git:(master) ✗ sudo ./install
Webcam parameters: '640' and '480'
Building v4l2loopback-dc.ko
make: Entering directory '/home/srajendran/droidcam-64bit/v4l2loopback'
make -C /lib/modules/`uname -r`/build M=`pwd`
make[1]: Entering directory '/usr/src/kernels/5.5.15-200.fc31.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[1]: Leaving directory '/usr/src/kernels/5.5.15-200.fc31.x86_64'
make: Leaving directory '/home/srajendran/droidcam-64bit/v4l2loopback'
Moving driver and executable to system folders
Registering webcam device
insmod: ERROR: could not insert module /lib/modules/5.5.15-200.fc31.x86_64/kernel/drivers/media/video/v4l2loopback-dc.ko: Operation not permitted
```
```bash
➜  droidcam-64bit git:(master) ✗ sudo modprobe v4l2loopback-dc
modprobe: ERROR: could not insert 'v4l2loopback_dc': Operation not permitted
```

I you have any ideas, it will be very usefull.

Thank you in advance

**Comment by aramg** [comment]
Do you have secure boot enabled in your bios?
See https://github.com/aramg/droidcam/issues/21

**Comment by fernandopc85** [comment]
i have error

Webcam parameters: '640' and '480'
Building v4l2loopback-dc.ko
make: se entra en el directorio '/tmp/droidcam/v4l2loopback'
make -C /lib/modules/`uname -r`/build M=`pwd`
make[1]: se entra en el directorio '/usr/src/kernels/5.5.17-200.fc31.x86_64'
  AR      /tmp/droidcam/v4l2loopback/built-in.a
  CC [M]  /tmp/droidcam/v4l2loopback/v4l2loopback-dc.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /tmp/droidcam/v4l2loopback/v4l2loopback-dc.mod.o
  LD [M]  /tmp/droidcam/v4l2loopback/v4l2loopback-dc.ko
make[1]: se sale del directorio '/usr/src/kernels/5.5.17-200.fc31.x86_64'
make: se sale del directorio '/tmp/droidcam/v4l2loopback'
Secure Boot is enabled, attempting to sign the driver
please specify signing key location (or leave empty to sign manually later)

Enter the path of the public key: 
Enter the path of the private key: 
Moving driver and executable to system folders
+ cp v4l2loopback/v4l2loopback-dc.ko /lib/modules/5.5.17-200.fc31.x86_64/kernel/drivers/media/video/
+ cp droidcam /usr/bin/
+ cp droidcam-cli /usr/bin/
+ set +x
Registering webcam device
insmod: ERROR: could not insert module /lib/modules/5.5.17-200.fc31.x86_64/kernel/drivers/media/video/v4l2loopback-dc.ko: Operation not permitted
warning: device not registered
Running depmod
make: se entra en el directorio '/tmp/droidcam/v4l2loopback'
make -C /lib/modules/`uname -r`/build M=`pwd` clean
make[1]: se entra en el directorio '/usr/src/kernels/5.5.17-200.fc31.x86_64'
  CLEAN   /tmp/droidcam/v4l2loopback/Module.symvers
make[1]: se sale del directorio '/usr/src/kernels/5.5.17-200.fc31.x86_64'
make: se sale del directorio '/tmp/droidcam/v4l2loopback'
Adding uninstall script
Done

**Comment by fernandopc85** [comment]
![image](https://user-images.githubusercontent.com/64717851/80898629-4c070680-8ccb-11ea-97e1-9ce1619eaadc.png)

**Comment by aramg** [comment]
Hi, As the output of the script says, you have secure boot enabled.
You either need to disable it in your bios, or sign it manually.
https://docs.fedoraproject.org/en-US/Fedora/21/html/System_Administrators_Guide/sect-signing-kernel-modules-for-secure-boot.html

**Comment by lery-susanto** [comment]
> Hi, As the output of the script says, you have secure boot enabled. You either need to disable it in your bios, or sign it manually. https://docs.fedoraproject.org/en-US/Fedora/21/html/System_Administrators_Guide/sect-signing-kernel-modules-for-secure-boot.html

The link is broken.
