### ISSUE TITLE
setup USB connection via gui client crashes during connection

### ISSUE THREAD

**Issue by lockejan** [aramg/droidcam#42]
Hi,
the connection is working via wifi already, but it crashes during usb connection via the gui-client.

1. It asks me for my (android) passcode.
2. The client on X then crashes like so:

```
droidcam: XlibInt.c:238: _XPrivSyncFunction: Assertion `dpy->synchandler == _XPrivSyncFunction' failed.
[1]    306304 abort (core dumped)  droidcam
```

I'm on fedora 31 with X

I then tried it via the cli like so `droidcam-cli 127.0.0.1 4747`
That works without crashes.

**Comment by rdorsch** [comment]
On Debian 10 I have it running also in the gui (w/o passcode)

rd@h370:~$ droidcam

(droidcam:20699): Gtk-WARNING **: 12:54:12.067: Unable to locate theme engine in module_path: "hcengine",

(droidcam:20699): Gtk-WARNING **: 12:54:12.068: Unable to locate theme engine in module_path: "hcengine",
Device: Droidcam
Found driver: /dev/video0 (fd:7)
connecting to 127.0.0.1:4747
