### ISSUE TITLE
Does not detect the microphone

### ISSUE THREAD

**Issue by srpaquito** [aramg/droidcam#43]
I have installed the app for Linux in Ubuntu 18.04 and in KDE neon. Neither of the two distros detects the mobile's microphone.

I have tried it with two phones, a BQ Aquaris U Plus and a Huawei P20 Lite.

The problem is, surely, from the application for Linux, because I have tested it on Windows 10 and with either of the two phones the microphone works perfectly.

Could you help me

Thank you.

**Comment by aramg** [comment]
Hi, as stated on top of the apps Linux page and as per #1 the Linux client is video only as of now.

**Comment by srpaquito** [comment]
Thank you very much for responding so quickly.

Too bad the microphone doesn't work on Linux.

Saúdos.
