### ISSUE TITLE
[android] White Balance Menu 

### ISSUE THREAD

**Issue by AndyHee** [aramg/droidcam#44]
The menu for adjusting the white balance presents the options in a random way. Would it not be better to list options based on an increase of temperature?

Also it may also improve usability to have the Kelvin value displayed in brackets: e.g. "Incandescent (2400 K)"

**Comment by aramg** [comment]
The list is copied from the Android documentation, in no particular order.
If paste a suggested alternative order, I can update the app menu with it.

**Comment by AndyHee** [comment]
OK, great! 

I'll paste the order based on the light temperature shortly. Let me just do some brief testing beforehand. 

Would you mind to point me to the android documentation that deals with this. For some reasons one of the presets (i.e. "Twilight") seems have an unusual value.

Many thanks!

**Comment by aramg** [comment]
See 
https://developer.android.com/reference/android/hardware/camera2/CameraMetadata#CONTROL_AWB_MODE_AUTO 

and the older API which has less details
https://developer.android.com/reference/android/hardware/Camera.Parameters#WHITE_BALANCE_AUTO

**Comment by AndyHee** [comment]
-  Automatic
-  Incandescent
-  Warm Fluorescent (2940 K)
-  Sunrise/ Sunset
-  Fluorescent (4230 K)
-  Daylight (6504 K)
-  Cloudy Daylight
-  Shade


This order is from the warmest (lowest temperature) to the coldest  (highest temperature) light source. 

I have added temperature values in brackets based on the CIE standards as stated in the android documentation for these three pre-settings. This presumably gives a clearer pinpoint in the broad _range_ of these pre-setting names. (See [here for example)](https://www.cambridgeincolour.com/tutorials/white-balance.htm)

I also suggest to rename the so-called "Twilight". As far I can see (tested with two different devices), this is nowhere near a twilight light. Twilight is the coldest  light; it's blueish. This means White Balancing would turn a daylight picture very warm, warmer than the "Shade" setting. I believe this android bug/ mislabelling stems from the confusion that twilight occurs immediately before sunrise or after sunset. (See [here]( https://www.photopills.com/articles/understanding-golden-hour-blue-hour-and-twilights).) However the actual white balance value, from what I can see relates to is "Sunrise/ Sunset" which is somewhere around 3000-4000 K; hence this presetting is for a warm light source and not the super cool twilight around 10,000+ K.

Finally I suggest to rename "Auto" to "Automatic" in line with a more natural use of languages.

**Comment by AndyHee** [comment]
So sought further advise on the twilight issue. Its not usual to use this very broad term the way the Android document does. So this is the order:

-  Automatic
-  Incandescent
-  Warm Fluorescent (2940 K)
-  Twilight 
-  Fluorescent (4230 K)
-  Daylight (6504 K)
-  Cloudy Daylight
-  Shade

**Comment by aramg** [comment]
Amazing. I'll make this change as part of the next update very soon.

**Comment by aramg** [comment]
The beta track of DroidCam got updated today and includes these changes.
Barring any other issues, it'll be rolling out over the next couple days.
Thanks again 👍
