### ISSUE TITLE
Client GUI freezes when clicking "Connect" on Fedora 32

### ISSUE THREAD

**Issue by serovar** [aramg/droidcam#52]
I compiled the client without problems on Fedora 32, but when I click "Connect" the program freezes completely until it says:

```
Connect failed, please try again.
Check IP and Port.
Check network connection.
```

droidcam-cli instead works perfectly fine.

**Comment by aramg** [comment]
Do you get this even if the IP is correct? 
It will freeze if you try to connect to an invalid IP.

**Comment by serovar** [comment]
Yesterday I thought I tried it with the same IP as droidcam-cli and it gave that problem, but I tried again now and it works, so probably I accidentally wrote the IP incorrectly, sorry for the trouble!

**Comment by aramg** [comment]
I'll fix this anyway, the default system timeout for a failed connection is way too long
