### ISSUE TITLE
config setting for connection mode (wifi/lan, wifi server, usb)

### ISSUE THREAD

**Issue by ensonic** [aramg/droidcam#55]
would you mind a pr to configure the selected connection mode for the linux client? I am using USB and would like to avoid having to select this each time. Especially my kids who started using it while doing school vc's often forget this.
Also do you mind adding ~/.config/droidcam to the search-path for the config and making it the default (that'd be inline with where configs should be stored).
Finally, did you consider using https://developer.gnome.org/glib/stable/glib-Key-value-file-parser.html to have the settings in ini format?

**Comment by brackenhill-mob** [comment]
+1

**Comment by aramg** [comment]
The sound support branch includes a change to save/restore the connection mode.

Not sure what you mean about the ~/.config/droidcam being in the search path, search path for what?

And for the config format change, that would be "nice to have", PRs welcome. Not sure I'll have the time for it anytime soon.

**Comment by ensonic** [comment]
I run strace on the stable droidcam and it looked for a file in ~/.droidcam/settings. In linux that is not a good practise anymore (it clutters the home dir and many backup programms suggest to backup ~/.config/ by default). I was suggesting to store the config in ~/.config/droidcam (if a single file is enough) or ~/.config/droidcam/settings if you prefer a subdir. With search path I mean that the code could search first in the new location and then check the legacy location (~/.droidcam/settings) to backwards compat.

I'll try the sound support branch and I can find some time in the evening to send you a PR for the keyfile support.

**Comment by aramg** [comment]
Right, yes, we can definitely move the location of the file, thats no big deal
