### ISSUE TITLE
Turn on flash via droidcam-cli

### ISSUE THREAD

**Issue by theapache64** [aramg/droidcam#58]
is there any option to turn on flash via `droidcam-cli` ?

**Comment by aramg** [comment]
Not right now, but it wouldn't be hard to add.
How do you think it should work?

**Comment by theapache64** [comment]
To start camera with flash on
`droidcam-cli <ip> <port> -f`

To start camera with  flash off
`droidcam-cli <ip> <port> -f 0`

or Do you have better suggestion ? :thinking:

**Comment by aramg** [comment]
Yea, its either a command line option (ie. the light is on the whole time), or its a toggle while the client is running (ie. you type in commands into the terminal).
I'll note this as a to-do.

**Comment by theapache64** [comment]
Alright. :+1:

**Comment by aramg** [comment]
Added some simple command parsing to droidcam-cli (while streaming), can you give this a try?
www.dev47apps.com/files/linux/droidcam_cli_12.zip

Once connected, enter ? for a list of options.
```
A/a: Auto-focus
L/l: Toggle Flash
-/=: Zoom Out
+: Zoom In
```

**Comment by yousif51811** [comment]
> Added some simple command parsing to droidcam-cli (while streaming), can you give this a try? [www.dev47apps.com/files/linux/droidcam_cli_12.zip](http://www.dev47apps.com/files/linux/droidcam_cli_12.zip)
> 
> Once connected, enter ? for a list of options.
> 
> ```
> A/a: Auto-focus
> L/l: Toggle Flash
> -/=: Zoom Out
> +: Zoom

> Added some simple command parsing to droidcam-cli (while streaming), can you give this a try? [www.dev47apps.com/files/linux/droidcam_cli_12.zip](http://www.dev47apps.com/files/linux/droidcam_cli_12.zip)
> 
> Once connected, enter ? for a list of options.
> 
> ```
> A/a: Auto-focus
> L/l: Toggle Flash
> -/=: Zoom Out
> +: Zoom In
> ```

Is this possible on windows?
