### ISSUE TITLE
Sound Support follow up

### ISSUE THREAD

**Issue by aramg** [aramg/droidcam#60]
Sound support is now live on the website.
Problems/issues/suggestions can go here, replacing #54 .

**Comment by guillermoml** [comment]
Linux Mint 19.3:

1. Executed `install` and `install-sound` without issues.
2. Launched `droidcam`, but showed an error: `snd_aloop` was not loaded. The module was correctly inserted in  ` /etc/modules-load.d/droidcam.conf` but I think the script didn't loaded it, so I had to load it manually with `sudo modprobe snd_aloop` (on next reboot it loaded correctly)
3. Then I launched droidcam and after that I executed `pacmd load-module module-alsa-source device=hw:Loopback,1,0 source_properties=device.description=droidcam_audio`  renaming it using @ensonic trick in https://github.com/aramg/droidcam/issues/54#issuecomment-629617090
4. In pavucontrol I found a new Input Device called _droidcam_audio_ as intended.
5. Connected droidcam and worked fine.
6. Oddly in Skype I choose _droidcam_audio_ as microphone, but the audio didn't work. I went to `pavucontrol` and found that in _recording_ tab Skype was connected to "Internal Audio". After I changed it to "droidcam_audio" it worked perfectly.

Thanks @aramg !

**Comment by DaftHonk** [comment]
Ubuntu 20.04:

1. I built from source in order to execute `./install-dkms` - no issues encountered.
2. Executed `./install-sound` - no issues.
3. Launch `droidcam` from terminal then run `pacmd load-module module-alsa-source device=hw:Loopback,1,0 source_properties=device.description=droidcam_audio` in a separate terminal. I am able to select `droidcam_audio` as my sound source in Zoom, no issues.

My main issue seems to be that the Loopback devices created become my defaults in PulseAudio/Gnome. This may be more of a PA issue than a droidcam issue, but it is a bit frustrating.
![Screenshot from 2020-05-26 12-36-13](https://user-images.githubusercontent.com/6444677/82921306-9daf5380-9f4e-11ea-8258-828dd3556d7e.png)

**Comment by arantxax** [comment]
Hello,
I installed Droidcam at my Ubuntu 20.04 using the instructions in [the official website](https://www.dev47apps.com/droidcam/linuxx/) and gave up on it after realizing that the audio wasn't working. For that, I runned:
`sudo /opt/droidcam-uninstall`
`sudo rm -Rf /opt/droidcam*`
`sudo rm -Rf /usr/bin/droidcam`
`sudo rm -Rf /usr/share/applications/droidcam.desktop`

After a while I decided to check the news in aramg's Twitter and I came up here, motivated by your sucessfull improvement. I cloned the repo and runned `sudo ./install`. Unfortunately it resulted in:

`Webcam parameters: '640' and '480'
Building v4l2loopback-dc.ko
make: Entering directory '/home/arantxa/webcam/droidcam/linux/v4l2loopback'
make -C /lib/modules/5.4.0-33-generic/build M=/home/arantxa/webcam/droidcam/linux/v4l2loopback modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-33-generic'
  CC [M]  /home/arantxa/webcam/droidcam/linux/v4l2loopback/v4l2loopback-dc.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC [M]  /home/arantxa/webcam/droidcam/linux/v4l2loopback/v4l2loopback-dc.mod.o
  LD [M]  /home/arantxa/webcam/droidcam/linux/v4l2loopback/v4l2loopback-dc.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-33-generic'
make: Leaving directory '/home/arantxa/webcam/droidcam/linux/v4l2loopback'
./install: line 24: mokutil: command not found
Adding uninstall script
Moving driver and executable to system folders
+ cp v4l2loopback/v4l2loopback-dc.ko /lib/modules/5.4.0-33-generic/kernel/drivers/media/video/
+ cp droidcam /usr/bin/
cp: it was not possible to get the status of 'droidcam': file or directory doesn't exist
`
I don't know what that means.

**Comment by aramg** [comment]
> I don't know what that means. Maybe it's related with the previous installation.

When you clone the repo, you get the source code.
You can download the latest binaries from the website, or here under the Releases section of the repo: https://github.com/aramg/droidcam/releases

**Comment by AbdoMahfoz** [comment]
Sound is working correctly, thanks <3

Is it possible to have load_module command run by default whenever droidcam is opened? 
I am trying to streamline the process as much as possible 😅

**Comment by AbdoMahfoz** [comment]
Also, is there anyway to imporve the audio quality ?
I managed to get a much better audio quality with another app that let me choose the sound source, can some similar behavior be done here ?
![image](https://user-images.githubusercontent.com/29104356/84044891-6e660100-a9a8-11ea-8b1f-15641fb30bda.png)

**Comment by aramg** [comment]
> Sound is working correctly, thanks <3
> 
> Is it possible to have load_module command run by default whenever droidcam is opened?
> I am trying to streamline the process as much as possible 😅

You can edit the PA config to make it permanent, as described [here](https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Microphone).

Increasing the sound sampling rate has been on my to-do list for some time, will get to it eventually. The app currently uses Speex which is older, so this requires changing the the whole codec.

**Comment by AbdoMahfoz** [comment]
I did that but it doesn't work. The droid mic input device would appear but it will be silent. I have to restart PA after droid cam is opened for it to work. It stays working after that till the next restart.

**Comment by aramg** [comment]
> I did that but it doesn't work. The droid mic input device would appear but it will be silent. I have to restart PA after droid cam is opened for it to work. It stays working after that till the next restart.

OK, then its PA being finicky. I guess your other option would be just put the load_module (or PA restart) and droidcam commands into a shell script, make it executable, and run that.

eg. `start_droidcam.sh`
```
#!/bin/bash
set -e
pacmd load-module module-alsa-source ...
droidcam
```

**Comment by AbdoMahfoz** [comment]
The thing is, droidcam has to be running first before the module is loaded otherwise reloading it won't do anything. I thought about writing this script but then I would face a timing issue because something in droidcam must be loaded first before the sound module can be loaded. 
It needs to be done from within droidcam to guarantee that the module will be loaded after "something" has loaded

**Comment by aramg** [comment]
Right. PA seems to be behaving slightly different on different distros, so still learning. If a consistent approach gets figured out, I can have the client auto load everything.

For your case, you can just do this:
```
#!/bin/bash
set -e
droidcam &
sleep 1
pacmd load-module module-alsa-source ...
wait

**Comment by AbdoMahfoz** [comment]
Okay so if it will help, my distro is KDE neon current latest version, it is based on ubuntu 18.04 and probably it took PA from there untouched. In a few months KDE neon will be rebased to ubuntu 20.04. 

for now, I think the calls to `snd_output_stdio_attach` and `find_snd_device` on initialization are necessary for PA to load the module correctly in my configuration.

**Comment by ericballYT** [comment]
When I connect through WiFi with only audio enabled - it works fine. When I connect through WiFi with audio and video enabled - it works for 20 seconds and then somehow dies out. After 20 seconds it no longer picks up audio

**Comment by aramg** [comment]
I assume this is with the iOS app. I'll check the timeouts.

> When I connect through WiFi with only audio enabled - it works fine. When I connect through WiFi with audio and video enabled - it works for 20 seconds and then somehow dies out. After 20 seconds it no longer picks up audio

**Comment by ricardopieper** [comment]
I'm having some issues with audio only on Android:
I'm having an "Audio connection reset!" error every time I try to connect via USB. Wifi works but audio is breaking up.
I manage to get USB it working by connecting it via WiFI first, disconnect, then connect via USB. It works for some time, and then it dies out like @ericballYT said.

This is android, galaxy s8.

**Comment by junglized** [comment]
@DaftHonk Did you manage to sort out default device issue by any chance? I'm having a similar problem and can't find any solution to it.

**Comment by DaftHonk** [comment]
@junglized I don't think I ever did, unfortunately.

**Comment by kedricpon** [comment]
I have a problem, Droidcam change my default input and output sound device, everytime I boot my computer it switches to it. Im on Zorin Os(based on Ubuntu).

**Comment by kedricpon** [comment]
I fixed it by disabling the devices created by droidcam.
