### ISSUE TITLE
Big delays between Android and iPhone

### ISSUE THREAD

**Issue by ErunamoJAZZ** [aramg/droidcam#66]
Hi
First, I wanna say thank you for this amazing module, I was testing it and works great in Linux Mint 19.3 Tricia. However, I got some serious delays streaming when I tried it from an iPhone 5s (if compares with the Mi A3 I tried first). I'm not using that old iPhone since the Android is my main phone, and being honest, I'm sure many people could use their old iPhones like this one to get them a new use as webcam :P

I wanted to report an issue for the iPhone app, but, there is not a repository for that, so I'm doing it here.

My first thought was about a possible issue with the module, so I tried it the web (IP:PORT/video), then this was clear that the problem was in the iPhone side. There is a very long delay (around 1s ~ 2s) in iPhone.

You can see the problem in this video https://youtu.be/VxOCsLvO2_4
Android was close to realtime, but iPhone was very out of place lol

I think there are some reasons why this would be happening:
 1. wifi issues?: maybe iPhone 5s antenna is bad, idk, I got that phone from someone but I have never used it for enough time.
 2. slow compression?: of course the phone is doing that work, but Idk if CPU just do not can with the process.
 3. big source?: Thinking how improve the performance, idk if the image size that the app is using as source is just too big (since main record resolution in that phone is 1080p, idk if that could affect the amount of data to resize->compress).

For 1 and 2, the issue is the iPhone (gg old iPhones). but 3 is something that only the iOS developer could know.

I apologize for make this report here, I hope the iOS dev can know about this.

Thanks!

**Comment by aramg** [comment]
I actually have a iPhone 5S for testing, and it works much better than my old nexus 4, and just as good as the newer LG G6. 

The iPhone app is very straightforward and there is little to optimize. I think the 5S can only use 2.4Ghz WiFi, so maybe thats the problem? Unfortunately I haven't had a chance to integrate Apple USB support into the Linux client yet.

**Comment by ErunamoJAZZ** [comment]
About wifi at 2.4Ghz, my router does not have 5Ghz so both devices (5s and A3) are connected to 2.4Ghz frequency. Also, my PC is connected using cable not wifi.
Of course, 2.4Ghz is a high used range, not only for WiFi but Bluetooth, wireless phones, and many other devices use that frequency, but since my Mi A3 does not had any delay, I just ignored that possibility (that the problem was the wifi).

I wanna test with other iPhones, Androids, and routers in the future, after quarantine is over where I am.

**Comment by aramg** [comment]
The encoders on both Android and iOS are the same. Since the Mi is working good, it could be the hardware on your iPhone has gotten slower. Of course if I get more reports of slowness, I would look into it more, but so far the iOS app has been trouble free.

**Comment by ErunamoJAZZ** [comment]
I have been testing the app in windows too, using wifi and cable.
Using cable had a very good behavior, but using wifi in windows was the same as in linux, so yeah, it's a +1 for network in iPhone as the main reason.

Also, it's interesting how the first seconds the video is going well but after like 5~10sec its syncronization go worst.
