### ISSUE TITLE
Integration of libjpeg-turbo

### ISSUE THREAD

**Issue by ElektroVirus** [aramg/droidcam#71]
Hi, this is a great software which I have been using before.

But now that I try to install (compile from source) on Gentoo Linux, I installed _libjpeg-turbo_  as this package
[](https://packages.gentoo.org/packages/media-libs/libjpeg-turbo).

But the Makefile expects the _libjpeg-turbo_ is installed in _/opt_, which is now not the case.
Can this please be fixed? 

ElektroVirus

**Comment by aramg** [comment]
Hi, thats by design to make distributing the client easier. 
If you want to compile the shared lib, use
make JPEG_DIR="" JPEG_INCLUDE="" JPEG_LIB="" JPEG=$(pkg-config --libs --cflags libturbojpeg)

**Comment by ElektroVirus** [comment]
Thank you, I got this working! 

Should this info be added to README so that this question is not asked twice? :)
