### ISSUE TITLE
Error: Not a JPEG file

### ISSUE THREAD

**Issue by 0av** [aramg/droidcam#72]
Hello,

when I start Droidcam and connect with the smartphone I get following error:
```
tjDecompressHeader3()` failure: 1
Not a JPEG file: starts with 0x00 0x00
```

- libjpeg-turbo-2.0.4 installed with .deb-binarie
- Droid version: Latest (2020-06-04)
- System: Debian Buster

**Comment by aramg** [comment]
Donno, does the release binary work?

**Comment by 0av** [comment]
> Donno, does the release binary work? 
Yes. I also tested a self compiled version; same probem.

**Comment by 0av** [comment]
Problem solved.
The app on the smartphone was not updated.
