### ISSUE TITLE
EFI variables are not supported on this system

### ISSUE THREAD

**Issue by PedroExpedito** [aramg/droidcam#74]
Webcam parameters: '640' and '480'
Building v4l2loopback-dc.ko
make: Entrando no diretrio '/home/pedro/Downloads/droidcam/linux/v4l2loopback'

make -C /lib/modules/5.6.0-2-amd64/build M=/home/pedro/Downloads/droidcam/linux/v4l2loopback modules
make[1]: Entrando no diretrio '/usr/src/linux-headers-5.6.0-2-amd64'

  MODPOST 1 modules
make[1]: Saindo do diretrio '/usr/src/linux-headers-5.6.0-2-amd64'

make: Saindo do diretrio '/home/pedro/Downloads/droidcam/linux/v4l2loopback'

EFI variables are not supported on this system
Adding uninstall script
Moving driver and executable to system folders
+ cp v4l2loopback/v4l2loopback-dc.ko /lib/modules/5.6.0-2-amd64/kernel/drivers/media/video/
+ cp droidcam /usr/bin/
cp: no foi possvel obter estado de 'droidcam': Arquivo ou diretrio inexistente

**Comment by aramg** [comment]
> EFI variables are not supported on this system

Thats fine, its just checking if secure boot is on.

You cant install by just closing the repo, use https://github.com/aramg/droidcam/releases
