### ISSUE TITLE
(Linux) Is resolution determined client-side or phone-side?

### ISSUE THREAD

**Issue by ngoonee** [aramg/droidcam#75]
I can change my modprobe options to select resolution. How do I figure out whether my resolution is 'correct' for my phone? Neither the android app nor the Linux client shows the resolution of the stream. By trial and error I think 420p is 640x480 for my phone rather than the 'normal' 740x480 which gives a distorted view for me.... not sure if this is the same for all droidcam or it depends on the phone. Also once I go for Pro not sure what the ratio is going to be.

**Comment by aramg** [comment]
The size determined on the phone, the app will pick closest available option based on the webcam setting on the computer. 
640x480 is the normal one for 480p, I've never seen 740x480 used anywhere before. https://en.wikipedia.org/wiki/480p

**Comment by ngoonee** [comment]
@aramg on Linux the app chooses 320x240 for me, and I have to manually modprobe to 640x480 to get that resolution. I think on Windows it works as you described (based on my testing on my mother-in-law's machine).

**Comment by aramg** [comment]
Do you get 320x240 when you have 640x480 on the computer? Did you make sure to restart the client so picks up the correct option after the webcam is updated.

You can see the exact resolution the app picked in adb logcat. 
If you stick to the standard ones (like the Windows client) - 640×480, 960×720, 1280×720, 1920×1080 - thats what you should get from the phone. 
All other resolution options vary widely between different phones.

**Comment by ngoonee** [comment]
When I don't set anything I get 320x240. Of course when I insmod as instructed to 640x480 it comes out as 640x480.

So it seems the client will have a fixed resolution regardless on what the phone is sending?

**Comment by aramg** [comment]
OK, I see... if you load the driver without specifying any width and height option, it defaults to 320x240 

https://github.com/aramg/droidcam/blob/master/linux/v4l2loopback/v4l2loopback-dc.c#L146

(that code is 7 years old, never been changed thats why so low)

**Comment by ngoonee** [comment]
=) That explains it. I recommend upping that to 640x480 (I don't think any phone in current existance is less than that, nor are any working networks too slow for that.

Ideally it would auto-configure but I guess kernel modules aren't the easiest to do that in. Most linux users will know how to change it to their liking anyway, and you have documented it properly (I would use modprobe rather than insmod nowadays though).

**Comment by terencode** [comment]
I tried to modprobe the patched v4l2loopback with width and height higher than 480p but it does not seem like the app chooses anything else than 640x480.

**Comment by aramg** [comment]
The free app is limited to 480p.

**Comment by terencode** [comment]
Indeed, I just purchased the full version and it seems to work:
```
06-15 22:17:11.120 24703 24703 I 47      : StartCamera jpg_mode=4, want: w=1920 h=1080
06-15 22:17:11.122 24703 24703 I 47      : Try1> 1920x1080
06-15 22:17:11.123 24703 24703 I 47      : Try1< 1920x1080, format:17 bpp:12
```
