### ISSUE TITLE
Inconsistent latency

### ISSUE THREAD

**Issue by ngoonee** [aramg/droidcam#76]
I'm getting inconsistent latency on an android phone with a Linux host. Similar behaviour whether using wifi (5G) or USB. Everything works fine, but right now I'm trying to get a consistent latency.

Initial connection mostly seems to work fine, with minimal latency (a few frames at most). I can even record a few minutes on OBS and it would be almost perfectly synced between my lip movements and the audio signal (which is from a mic directly plugged to my USB audio interface).

At some point the latency jumps up significantly to roughly 2/3rds of a second. Once this has happened it stays there for the rest of the session. Disconnecting and reconnecting droidcam helps most of the time but not all the time.

The fact that it works with low latency some of the time means the problem isn't (or isn't only) buffering I guess? I can deal with a second or two of latency, but it would be nice if it was consistent so I can just set a fixed delay on the non-droidcam video feed in OBS and have everything sync up nicely....

**Comment by brackenhill-mob** [comment]
+1

That might also explain why I found the FPS rate drop from 30fps to 12fps. Only a reboot fixes.

**Comment by aramg** [comment]
I have a new potential release for the Linux client to address the latency buildup if you'd like to try it out?
https://www.dev47apps.com/files/linux/droidcam_14_rc1.zip

The update introduces a new dependency, `usbmuxd`, you'll need to have that installed.
eg. `sudo apt install usbmuxd`

**Comment by ngoonee** [comment]
Hi @aramg unfortunately I'm on Arch and our libusbmuxd is on a different version.  I can complile from git master though, would that include this rc1?

**Comment by aramg** [comment]
hmm, so the binary I build (on Lubuntu) doesn't work with the Arch libusbmuxd?
You'll want to v14 branch for the new code.

**Comment by ngoonee** [comment]
Thanks, compiled and running it now. Will leave it for a while and report the results =). Definitely slight latency right now (noticeable but minimal) but it'd be unrealistic to expect otherwise, I'm mostly concerned about whether it increases over time.

**Comment by aramg** [comment]
Try turning on "Limit FPS" on the phone side. Since you were getting delay buildup means the computer was a little slower than the phone, not enough to drop frames, but falling behind.

**Comment by ngoonee** [comment]
Even without doing that, the inconsistent latency seems to be much better. How do I check/confirm that the droidcam I'm using is actually from v14 and not master (from the app itself)? I think I did things correctly but since the visual appearance is identical would be good to have a way to check.

**Comment by aramg** [comment]
The new version has 2 USB options, ADB and iOS, and it should say 1.4 at the bottom.
