### ISSUE TITLE
iPhone not found by ADB on Linux

### ISSUE THREAD

**Issue by ericballYT** [aramg/droidcam#78]
Droidcam works perfectly over WiFi, but when I try to use USB with adb - it says 'No devices detected. Please refer to the website for manual adb setup info'. So I went to the website and the only thing I could find regarding Linux and USB was where it says 'USB connections: The client app will try to invoke adb automatically, provided adb is installed'. So I looked at the commands executed by droidcam and I tried to run them. I ran 'adb start-server' and 'adb devices' but the 'List of devices attached' is empty. I read on the 'connect' tutorial that iTunes is required to detect the iPhone. I tried downloading iTunes but it says that it cannot sync iDevices and 'List of devices attached' is still empty. 

Has anyone gotten iPhone to work through USB with Ubuntu 18.04?

**Comment by aramg** [comment]
Hi, Unfortunately I haven't had a chance to code in iOS USB support to the Linux client yet.
ADB is just for Android. Now that DroidCam OBS is out, I am planning to add iOS support to both the OBS plugin and the DroidCam Linux client in the near future, the code will be very similar.

**Comment by aramg** [comment]
Hi,
I have a new potential release for the Linux client with iOS USB support, if you'd like to try it out?
https://www.dev47apps.com/files/linux/droidcam_14_rc1.zip

Make sure `usbmuxd` is installed.

**Comment by ericballYT** [comment]
I'll try it out right now
