### ISSUE TITLE
Installed audio, but audio input not works..

### ISSUE THREAD

**Issue by vivekkj123** [aramg/droidcam#80]
Hi There,

I installed droidcam on linux mint 19.3 tricia...I also installed the sound file as mentioned in your page...But unfortunately i didn't getting audio input to my computer.. Please guide me to how to solve this problem....'
When i run the program i got an error showing that audio devices not found... What i do right now....Attaching the terminal output.. :)

`Device /dev/video0 is 'Droidcam'`
`Opened /dev/video0, fd:10`
`Channels count (1) not available for playbacks: Invalid argument`
`setting audio hwparams failed: Success`
`Audio loopback device not found.`
`Is snd_aloop loaded?`
`connecting to 192.168.1.100:4747
`

**Comment by aramg** [comment]
Did the install-sound script print any errors?
Are there any other apps using the loopback sound card?

**Comment by vivekkj123** [comment]
I didn't get any errors when I installed sound... 

> Are there any other apps using the loopback sound card?

How to know this?

**Comment by aramg** [comment]
Do you have any programs running that might have the audio input open (eg VLC, Discord, OBS, etc.)?
The error is because the DroidCam client fails to set the channel count on the device, from what I can tell this is unlikely to fail unless the audio device was already configured with some other channel count.

Could you paste the outputs of  `aplay -l`, `sudo lsof -nP /dev/snd/*`

**Comment by vivekkj123** [comment]
<pre><font color="#8AE234"><b>vivek@vivek</b></font>:<font color="#729FCF"><b>/</b></font>$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Intel [HDA Intel], device 0: ALC887-VD Analog [ALC887-VD Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Intel [HDA Intel], device 1: ALC887-VD Digital [ALC887-VD Digital]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
</pre>

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
<pre><font color="#8AE234"><b>vivek@vivek</b></font>:<font color="#729FCF"><b>/</b></font>$ sudo lsof -nP /dev/snd/*
lsof: WARNING: can&apos;t stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
COMMAND    PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
pulseaudi 1690 vivek   17u   CHR 116,12      0t0  512 /dev/snd/controlC0
pulseaudi 1690 vivek   24u   CHR 116,12      0t0  512 /dev/snd/controlC0
pulseaudi 1690 vivek   31u   CHR  116,6      0t0  497 /dev/snd/controlC1
pulseaudi 1690 vivek   38u   CHR  116,6      0t0  497 /dev/snd/controlC1
</pre>

**Comment by vivekkj123** [comment]
I have VLC, Audacity, Pulseaudio control And Kdenlive Only....

**Comment by vivekkj123** [comment]
> Hi There,
> 
> I installed droidcam on linux mint 19.3 tricia...I also installed the sound file as mentioned in your page...But unfortunately i didn't getting audio input to my computer.. Please guide me to how to solve this problem....'
> When i run the program i got an error showing that audio devices not found... What i do right now....Attaching the terminal output.. :)
> 
> `Device /dev/video0 is 'Droidcam'`
> `Opened /dev/video0, fd:10`
> `Channels count (1) not available for playbacks: Invalid argument`
> `setting audio hwparams failed: Success`
> `Audio loopback device not found.`
> `Is snd_aloop loaded?`
> `connecting to 192.168.1.100:4747 `

The error message also disappeared when i reinstalled droidcam.. But still sound not works

**Comment by aramg** [comment]
Hmm, everything looks OK.
Do you get a "audio connected" message on the phone?
Try connecting with just audio, the phone will show a picture of a microphone instead of camera preview. Make sure you connect DroidCam first, only then open VLC/etc.
Not sure what else I can recommend.

**Comment by vivekkj123** [comment]
I got message audio connected... But audio input not working.... Let I check any other methods for fixing this issue

**Comment by vivekkj123** [comment]
I will reopen and update this thread when I fix the error… Anyway thank you for your support... ☺️
