### ISSUE TITLE
droidcam set default device

### ISSUE THREAD

**Issue by seedship** [aramg/droidcam#81]
How do I set the default device on droidcam? When I start it up from CLI with the default settings, it uses /dev/video0. Is there a way I can change that?

**Comment by aramg** [comment]
What would you like to change it to?

`/dev/videoX` is created by V4L2 Loopback sub-system AFAIK. I don't know if it's possible to specify which number to use when inserting a new device, its just sequential.

**Comment by seedship** [comment]
I have /dev/video0-4. /dev/video0 used to by my linux webcam, but now it is droidcam, and my linux webcam is now /dev/video1. Is there a way I can remap droidcam to a different /dev/video?

**Comment by aramg** [comment]
I assume the order depends on which drivers get loaded first.

The droidcam v4l2 device loads via `/etc/modules-load.d/droidcam.conf`, you can look in the same directory for any references to your regular webcam. If there are none, you could remove the droidcam conf file to ensure the webcam gets loaded first on boot, and enable droidcam manually later using `modprobe v4l2loopback_dc`.

There could be a way to specify the preferred /dev/video number in V4L2, but I'm not sure how/where.
