### ISSUE TITLE
v1.4 lost ability to zoom

### ISSUE THREAD

**Issue by brackenhill-mob** [aramg/droidcam#84]
On previous versions there was an ability on the main screen to zoom in which was useful as I could cut out the clutter in my office so my clients couldn't see!

On v1.4 this has gone (or I can't find the setting anymore!)

Please can we have it back? Pretty please!!

**Comment by brackenhill-mob** [comment]
Ignore this - it's in the Android apk v6.8 not the Linux client. Doohh!

**Comment by aramg** [comment]
The latest apps do pinch-zoom now.
I tried to keep both the slider and add the pinch but it was tricky to keep the level in sync between the two.
