### ISSUE TITLE
Space in source directory causing failure during install (Linux)

### ISSUE THREAD

**Issue by clay53** [aramg/droidcam#86]
Note: ``gcc make linux-headers-`uname -r` `` does not work as a preface to the install as shown on https://www.dev47apps.com/droidcam/linux/ so that may be related
returns:
```
gcc: error: make: No such file or directory
gcc: error: linux-headers-5.4.0-7634-generic: No such file or directory
gcc: fatal error: no input files
compilation terminated.
```

The return from `sudo ./install` is:
```
Webcam parameters: '640' and '480'
Building v4l2loopback-dc.ko
make: Entering directory '/home/clay53/Downloads/OK Delete/droidcam/v4l2loopback'
make -C /lib/modules/5.4.0-7634-generic/build M=/home/clay53/Downloads/OK Delete/droidcam/v4l2loopback modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-7634-generic'
arch/x86/Makefile:147: CONFIG_X86_X32 enabled but no binutils support
make[1]: *** No rule to make target 'Delete/droidcam/v4l2loopback'.  Stop.
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-7634-generic'
make: *** [Makefile:8: all] Error 2
make: Leaving directory '/home/clay53/Downloads/OK Delete/droidcam/v4l2loopback'
```

Then checking to see if it succeed (which it didn't - `lsmod | grep v4l2loopback_dc` ) returns nothing.

**Comment by clay53** [comment]
Just found that moving it to the `/tmp` folder fixes the issue (realized this from reading line 7 from `sudo ./install`). This is still an issue as spaces in directories should not cause such issues.

**Comment by aramg** [comment]
For spaces in directories see: https://github.com/aramg/droidcam/issues/37#issuecomment-621602046

For the gcc, make, etc. line - the instructions say "Ensure the following dependencies are installed (**using apt-get, yum, etc.**)". On Ubuntu, thats `sudo apt-get install gcc make ...`
