### ISSUE TITLE
Provide a single instruction for building in website and readme

### ISSUE THREAD

**Issue by apandada1** [aramg/droidcam#88]
In the [website](https://www.dev47apps.com/droidcam/linux/), it is not very clear how to install droidcam. It does not say that one has to first install the dependencies and `libjpeg-turbo` and then run `make` before trying to run `./install.sh` (or the dkms version).

It took me a long time to realize how to install Droidcam. Also, recent versions of Ubuntu and Arch support DKMS, so it may be a good idea to suggest to install the DKMS version by default.

Also, it would be very useful if the readme and the website are rewritten like [this comment](https://github.com/aramg/droidcam/issues/6#issuecomment-657477309).

**Comment by aramg** [comment]
???
The instructions on the website don't require make and have minimal dependencies.

Extra dependencies like libjpeg-turbo and running make are only needed if you want to build+install from the source here on GitHub where the README has the steps.

**Comment by apandada1** [comment]
Oops. I saw that `32 bit binaries are no longer provided`, and thought that everyone (even 64 bit users) has to build from source.

However, it would be great if the special steps for build instruction for Raspberry Pi (based on https://github.com/aramg/droidcam/issues/6#issuecomment-657477309) are given in the Readme itself.

I am closing the issue.

**Comment by aramg** [comment]
Yea I think its about time I buy a Pi and just try it out.
Just havent had the need for one
