### ISSUE TITLE
Binaries from the releases page fail to install with kernel 5.4

### ISSUE THREAD

**Issue by apandada1** [aramg/droidcam#89]
**OS**: Linux Mint 19.3, 64 bit
**Kernel**: `5.4.0-42-generic`
**Method of installation**: Executed `sudo ./install` after extracting `droidcam_1593923604.zip` (v1.4) from the releases page.

It fails to install with Kernel 5.4.
**Output**: See attached [kernel5.4.log](https://github.com/aramg/droidcam/files/5068679/kernel5.4.log)

**May be related** - Compatibility with Kernel 5.4 was recently [added to upstream v4l2loopback](https://github.com/umlaeute/v4l2loopback/blob/master/NEWS#L3).

**Compare** Kernel `5.3.0-40-generic`, where it installs and works  _successfully_.
```
##Output for Kernel 5.3.0-40-generic##
:~/droidcamdebpackage/droidcam_1593923604$ sudo ./install
     
Webcam parameters: '640' and '480'
Building v4l2loopback-dc.ko
make: Entering directory '/home/archisman/droidcamdebpackage/droidcam_1593923604/v4l2loopback'
make -C /lib/modules/5.3.0-40-generic/build M=/home/archisman/droidcamdebpackage/droidcam_1593923604/v4l2loopback modules
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-40-generic'
  CC [M]  /home/archisman/droidcamdebpackage/droidcam_1593923604/v4l2loopback/v4l2loopback-dc.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/archisman/droidcamdebpackage/droidcam_1593923604/v4l2loopback/v4l2loopback-dc.mod.o
  LD [M]  /home/archisman/droidcamdebpackage/droidcam_1593923604/v4l2loopback/v4l2loopback-dc.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-40-generic'
make: Leaving directory '/home/archisman/droidcamdebpackage/droidcam_1593923604/v4l2loopback'
Adding uninstall script
Moving driver and executable to system folders
+ cp v4l2loopback/v4l2loopback-dc.ko /lib/modules/5.3.0-40-generic/kernel/drivers/media/video/
+ cp droidcam /usr/bin/
+ cp droidcam-cli /usr/bin/
+ set +x
Registering webcam device
Running depmod
make: Entering directory '/home/archisman/droidcamdebpackage/droidcam_1593923604/v4l2loopback'
make -C /lib/modules/5.3.0-40-generic/build M=/home/archisman/droidcamdebpackage/droidcam_1593923604/v4l2loopback clean
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-40-generic'
  CLEAN   /home/archisman/droidcamdebpackage/droidcam_1593923604/v4l2loopback/Module.symvers
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-40-generic'
make: Leaving directory '/home/archisman/droidcamdebpackage/droidcam_1593923604/v4l2loopback'
Done
```

I also tried to `install-dkms` in Kernel 5.3, and then run droidcam in Kernel 5.4, but it says device not found, and I'll have to reinstall because there was a kernel update.

**Comment by apandada1** [comment]
I also tried building Droidcam from source and then running `./install` (both under Kernel 5.4), but the issue is present.

**Comment by aramg** [comment]
HI, all the errors in your log are related to the Linux internals, not v4l2loopback-dc. Something is messed up with your kernel v5.4 installation.
```
In file included from ./include/linux/bug.h:5:0,
                 from ./include/linux/thread_info.h:12,
                 from ./arch/x86/include/asm/preempt.h:7,
                 from ./include/linux/preempt.h:78,
                 from ./include/linux/spinlock.h:51,
                 from ./include/linux/vmalloc.h:5,
                 from /home/archisman/droidcamdebpackage/droidcam_1593923604/v4l2loopback/v4l2loopback-dc.c:24:
./arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
```

I am going to ask that you **NOT** package and distribute a PPA. 
My stance in general is against 3rd party packages, all you're going to do is create more support emails for me down the line.

**Comment by apandada1** [comment]
I would try a different 5.4 kernel. This error is there when I install from source or the .zip, it's not related to the PPA.

**Comment by alexeikh** [comment]
@apandada1, I've done some investigation for you.

The compilation issues seem to be related to `asm __inline`. You are using Linux Mint 19.3, which seems to have GCC 7.4.0 (got that info from https://unix.stackexchange.com/questions/562769/steam-not-working-in-linux-mint-19-3-mate).

Then, seems like GCC 7.4.0 does not support `inline` qualifier for `asm` (compare docs for GCC 7.4.0: https://gcc.gnu.org/onlinedocs/gcc-7.4.0/gcc/Extended-Asm.html and for GCC latest version: https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html).

Then, `asm __inline` is protected by the `CONFIG_CC_HAS_ASM_INLINE` macro, so it should not be a problem:
```c
#ifdef CONFIG_CC_HAS_ASM_INLINE
#define asm_inline asm __inline
#else
#define asm_inline asm
#endif
```

But seems like the `CONFIG_CC_HAS_ASM_INLINE` macro is defined anyway, even though it should not be, thus the compilation fails.

So, I see 2 solutions for you:
* Investigate further why the `CONFIG_CC_HAS_ASM_INLINE` macro is defined and fix it.
* Upgrade GCC to some version that supports `asm inline`.

**Comment by apandada1** [comment]
@alexeikh Great catch! It installed after upgrading to `gcc-8`.
