### ISSUE TITLE
A question about the forward proxy NGINX patch

### ISSUE THREAD

**Issue by vadimeisenbergibm** [aramg/droidcam#9]
Hi Aram,

Sorry for using this issue to contact you -  following your advice https://gist.github.com/aramg/4540f0f8cfb8922e89bd#gistcomment-1959333.

Could you please advise me on the status of that patch? Is it now a part of OpenResty release? If I download OpenResty, will I get this patch installed? You wrote in your blog: "_his new code has gone out to production just recently_". So is it part of OpenResty or do you apply the patch during your internal build process?

Thanks a lot for the great blog and the patch!

Vadim

**Comment by aramg** [comment]
Hello Vadim,
The patch is not part of OpenResty, since it alters nginxs "load balancing" behaviour. It is applied during the internal build process. The gist contains necessary changes for openresty 1.9.3, and it's expected you understand the internal workings of nginx to use it.
Hope that helps.

**Comment by vadimeisenbergibm** [comment]
Thanks Aram, now it is clear.
