### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [aramg/droidcam#92]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing DroidCam on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by aramg** [comment]
Closing as a dup for #49 

I think the way forward is to refactor the client to use the main v4l2loopback driver, at which point it'll be easy to package it.
