### ISSUE TITLE
keeps losing connection

### ISSUE THREAD

**Issue by michaelaye** [aramg/droidcam#94]
even so iphone and linux pc are on same wifi.

Not sure, it's related, but I can't Ctrl-C the shell where i started `droidcam-cli` either. 
Problem happens with both DKMS and without.
 
How could i debug this?

Thanks!

**Comment by michaelaye** [comment]
i'm on github head `1f2460a`

**Comment by aramg** [comment]
Sounds like the connection is getting stuck (the app is frozen in a recv call).
Try restarting the router.
